# Use postgres/example user/password credentials
version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq

  pusblish-subscribe:
    build:
      context: .
      dockerfile: Dockerfile
    restart:
      unless-stopped
      #- DB_HOST=host.docker.internal
    environment:
      - RABBIT_HOST=rabbitmq
    ports:
      - 3004:3001
    depends_on:
      - rabbitmq
